version: '3'

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecc-image
    container_name: ecc-container
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - ecc

  # Nginx service
  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - ecc
    depends_on:
      - app  # Ensure that the 'app' service is ready before starting 'web'
  
networks:
  ecc:
    driver: bridge
