<?php

namespace App\Http\Controllers\admin;

use App\Models\BibleStudy;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;


class BibleStudyController extends LaraCRUDController
{
    /**
     * @param BibleStudy $bibleStudy
     */
    public function __construct(BibleStudy $bibleStudy)
    {
        parent::__construct();

        $this->model = $bibleStudy;
        $this->limit = 10;
        $this->data['wysiwyg'] = true;


        $this->head = [
            array('field' => 'photo', 'title' => 'Photo', 'type' => 'image'),
            array('field' => 'type', 'title' => 'Type', 'text', 'database' => 'bible_types', 'where' => ''),
            array('field' => 'title_en', 'title' => 'Title (English)'),
            array('field' => 'caption_en', 'title' => 'Caption (English)'),
            array('field' => 'title_kh', 'title' => 'Title (Khmer)'),
            array('field' => 'caption_kh', 'title' => 'Caption (Khmer)'),
        ];

        $this->form = [
            array('field' => 'type', 'title' => 'Type', 'type' => 'select2', 'required' => true, 'validated' => 'required', 'database' => 'bible_types,id,name', 'where' => ''),
            array('field' => 'photo', 'title' => 'Photo', 'type' => 'file', 'required' => true, 'validated' => 'required', 'accept' => 'image/*'),
            array('field' => 'title_en', 'title' => 'Title (English)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'caption_en', 'title' => 'Caption (English)', 'type' => 'wysiwyg', 'required' => true, 'validated' => 'required'),
            array('field' => 'title_kh', 'title' => 'Title (Khmer)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'caption_kh', 'title' => 'Caption (Khmer)', 'type' => 'wysiwyg', 'required' => true, 'validated' => 'required'),
        ];
    }

    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->data['result'] = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @return Factory|View|Application
     */
    public function getAdd(): Factory|View|Application
    {
        $this->data['form'] = $this->form;
        $this->addRelation($this->form);
        return view('admin.add', ['data' => $this->data]);
    }


    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['back'] = "user";
        $this->data['form'] = $this->form;
        $this->addRelation($this->form);
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }


    /**
     * @param $id
     * @return mixed
     */
    public function detail($id): mixed
    {
        $this->data['find'] = $this->model->findOrFail($id);
        $this->data['title'] = 'Detail of ' . $this->model->moduleName;
        $this->data['back'] = $this->model->moduleName;
        $this->init();
        return view('admin.detail', ['data' => $this->data]);
    }
}
