<?php

namespace App\Http\Controllers\admin;

use App\Models\ContactUs;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class ContactUsController extends LaraCRUDController
{
    /**
     * @param ContactUs $contactUs
     */
    public function __construct(ContactUs $contactUs)
    {
        parent::__construct();

        $this->model = $contactUs;
        $this->limit = 10;
        $this->export = false;
        $this->data['wysiwyg'] = true;

        $this->head = [
            array('field' => 'photo', 'title' => 'Photo', 'type' => 'image'),
            array('field' => 'title_en', 'title' => 'Title (English)'),
            array('field' => 'address_en', 'title' => 'Address (English)'),
            array('field' => 'title_kh', 'title' => 'Title (Khmer)'),
            array('field' => 'address_kh', 'title' => 'Address (Khmer)'),
            array('field' => 'facebook', 'title' => 'Facebook'),
            array('field' => 'twitter', 'title' => 'Twitter'),
            array('field' => 'instagram', 'title' => 'Instagram'),
        ];


        $this->form = [
            array('field' => 'photo', 'title' => 'Photo', 'type' => 'file', 'required' => true, 'validated' => 'required', 'accept' => 'image/*'),
            array('field' => 'title_en', 'title' => 'Title (English)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'address_en', 'title' => 'Address (English)', 'type' => 'wysiwyg', 'required' => true, 'validated' => 'required'),
            array('field' => 'title_kh', 'title' => 'Title (Khmer)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'address_kh', 'title' => 'Address (Khmer)', 'type' => 'wysiwyg', 'required' => true, 'validated' => 'required'),
            array('field' => 'facebook', 'title' => 'Facebook', 'type' => 'text'),
            array('field' => 'twitter', 'title' => 'Twitter', 'type' => 'text'),
            array('field' => 'instagram', 'title' => 'Instagram', 'type' => 'text'),
        ];
    }


    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->data['result'] = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @return Factory|View|Application
     */
    public function getAdd(): Factory|View|Application
    {
        $this->title = "Add new contactUs";
        $this->data['form'] = $this->form;
        $this->data['back'] = $this->model->moduleName;
        return view('admin.add', ['data' => $this->data]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['back'] = $this->model->moduleName;
        $this->data['form'] = $this->form;
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function detail($id): mixed
    {
        $this->data['find'] = $this->model->findOrFail($id);
        $this->data['title'] = 'Detail of ' . $this->model->moduleName;
        $this->data['back'] = $this->model->moduleName;
        $this->init();
        return view('admin.custom.church_detail', ['data' => $this->data]);
    }
}
