<?php

namespace App\Http\Controllers\admin;

use App\Models\Font;
use Helper;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;

class FontController extends LaraCRUDController
{
    /**
     * @param Font $font
     */
    public function __construct(Font $font)
    {
        parent::__construct();

        $this->model = $font;
        $this->limit = 10;
        $this->export = false;

        $this->head = [
            array('field' => 'name', 'title' => 'Name'),
            array('field' => 'file', 'title' => 'File'),
        ];


        $this->form = [
            array('field' => 'name', 'title' => 'Name', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'file', 'title' => 'File', 'type' => 'file', 'required' => true, 'validated' => 'required', 'accept' => '.ttf'),
        ];
    }


    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->data['result'] = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @return Factory|View|Application
     */
    public function getAdd(): Factory|View|Application
    {
        $this->data['form'] = $this->form;
        $this->init();
        return view('admin.add', ['data' => $this->data]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['form'] = $this->form;
        $this->form[1] = array('field' => 'file', 'title' => 'File', 'type' => 'file', 'accept' => '.ttf');
        $this->init();
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function detail($id): mixed
    {
        $this->data['find'] = $this->model->findOrFail($id);
        $this->init();
        return view('admin.detail', ['data' => $this->data]);
    }

    /**
     * @param Request $request
     * @return Application|RedirectResponse|Redirector
     */
    public function postAdd(Request $request): Redirector|RedirectResponse|Application
    {
        $redirectUrl = $request->get('save');
        $fields = $request->except('_token', 'save');
        $request->validate($this->validationForm());
        $fields['file'] = Helper::imageUpload('fonts', $fields['file']);

        $this->model->create($fields);

        return redirect($redirectUrl)->with('message', 'The data has been added');
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function update(Request $request): mixed
    {
        $this->form[1] = array('field' => 'file', 'title' => 'File', 'type' => 'file', 'accept' => '.ttf');
        return parent::update($request);
    }
}
