<?php

namespace App\Http\Controllers\admin;

use App\Models\Library;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;


class LibraryController extends LaraCRUDController
{
    /**
     * @param Library $library
     */
    public function __construct(Library $library)
    {
        parent::__construct();

        $this->model = $library;
        $this->limit = 10;
        $this->data['wysiwyg'] = true;

        $this->head = [
            array('field' => 'thumbnail', 'title' => 'Thumbnail', 'type' => 'image'),
            array('field' => 'title_en', 'title' => 'Title (English)'),
            array('field' => 'description_en', 'title' => 'Description (English)'),
            array('field' => 'title_kh', 'title' => 'Title (Khmer)'),
            array('field' => 'description_kh', 'title' => 'Description (Khmer)'),
            array('field' => 'url', 'title' => 'URL'),

        ];

        $this->form = [
            array('field' => 'bible_study_id', 'title' => 'Bible Study', 'type' => 'select2', 'required' => true, 'validated' => 'required', 'database' => 'bible_studies,id,title_' . app()->getLocale(), 'where' => ''),
            array('field' => 'photo', 'title' => 'Thumbnail', 'type' => 'file', 'required' => true, 'validated' => 'required', 'accept' => 'image/*'),
            array('field' => 'file', 'title' => 'File', 'type' => 'file', 'required' => true, 'validated' => 'required', 'accept' => 'audio/mpeg, video/mp4'),
            array('field' => 'url', 'title' => 'URL', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'title_en', 'title' => 'Title (English)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'caption_en', 'title' => 'Description (English)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'title_kh', 'title' => 'Title (Khmer)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'caption_kh', 'title' => 'Description (Khmer)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
        ];
    }

    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->data['result'] = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @return Factory|View|Application
     */
    public function getAdd(): Factory|View|Application
    {
        $this->data['form'] = $this->form;
        $this->addRelation($this->form);

        return view('admin.add', ['data' => $this->data]);
    }


    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['back'] = "user";
        $this->data['form'] = $this->form;
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }


    /**
     * @param $id
     * @return mixed
     */
    public function detail($id): mixed
    {
        $this->data['find'] = $this->model->findOrFail($id);
        $this->data['title'] = 'Detail of ' . $this->model->moduleName;
        $this->data['back'] = $this->model->moduleName;
        $this->init();
        return view('admin.detail', ['data' => $this->data]);
    }
}
