<?php

namespace App\Http\Controllers\admin;

use App\Models\Page;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;


class PageController extends LaraCRUDController
{
    /**
     * @param Page $page
     */
    public function __construct(Page $page)
    {
        parent::__construct();

        $this->model = $page;
        $this->limit = 10;
        $this->title = "Page List";

        $this->head = [
            array('field' => 'parent_id', 'title' => 'Parent'),
            array('field' => 'name_en', 'title' => 'Name (English)'),
            array('field' => 'name_kh', 'title' => 'Name (Khmer)'),
            array('field' => 'slug', 'title' => 'Slug'),
        ];

        $this->form = [
            array('field' => 'parent_id', 'title' => 'Parent', 'type' => 'select2', 'database' => 'pages,id,name_'. app()->getLocale(), 'where' => 'parent_id,NULL'),
            array('field' => 'name_en', 'title' => 'Name (English)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'name_kh', 'title' => 'Name (Khmer)', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'slug', 'title' => 'Slug', 'type' => 'text', 'required' => true, 'validated' => 'required'),
        ];
    }

    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->data['result'] = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @return Factory|View|Application
     */
    public function getAdd(): Factory|View|Application
    {
        $this->title = "Add new ".$this->model->moduleName;
        $this->data['form'] = $this->form;
        $this->addRelation($this->form);
        $this->data['back'] = $this->model->moduleName;
        $this->init();
        return view('admin.add', ['data' => $this->data]);
    }


    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['back'] = "user";
        $this->data['form'] = $this->form;
        $this->addRelation($this->data['form']);
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }


    /**
     * @param $id
     * @return mixed
     */
    public function detail($id): mixed
    {
        $this->data['find'] = $this->model->findOrFail($id);
        $this->data['title'] = 'Detail of ' . $this->model->moduleName;
        $this->data['back'] = $this->model->moduleName;
        $this->init();
        return view('admin.detail', ['data' => $this->data]);
    }
}
