<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Province;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProvinceController extends LaraCRUDController
{
    /**
     * @param Province $country
     */
    public function __construct(Province $province)
    {
        parent::__construct();

        $this->model = $province;
        $this->limit = 10;
        $this->export = false;
        $this->title = "Province List";

        $this->head = [
            array('field' => 'country_id', 'title' => 'Country', 'join' => 'countries', 'on' => 'country_id,id', 'column' => 'countries.name as country_id'),
            array('field' => 'name', 'title' => 'Name'),
            array('field' => 'description', 'title' => 'Description'),
        ];


        $this->form = [
            array('field' => 'country_id', 'title' => 'Country', 'type' => 'select', 'required' => true, 'validated' => 'required', 'database' => 'countries,id,name', 'where' => ''),
            array('field' => 'name', 'title' => 'Name', 'type' => 'text', 'required' => true, 'validated' => 'required|unique:countries'),
            array('field' => 'description', 'title' => 'Description', 'type' => 'text'),
        ];
    }


    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->result = $this->getJoin($this->model,$this->head);
        $this->init();
        return view('admincrud.index', ['data' => $this->data]);
    }

    /**
     * @return Factory|View|Application
     */
    public function getAdd(): Factory|View|Application
    {
        $this->title = "Add new " . $this->model->moduleName;
        $this->data['form'] = $this->form;
        $this->data['back'] = $this->model->moduleName;

        foreach ($this->form as $form) {
            if (isset($form['database']) && $form['database']) {
                $database = explode(",", $form['database']);
                $table = $database[0];
                unset($database[0]);
                $query = DB::table($table)->select($database);
                if (isset($form['where']) && $form['where']) {
                    $cond = explode(",", $form['where']);
                    $query = $query->where($cond[0], '=', $cond[1]);
                }
                $query = $query->limit($this->limit)->get();
                $this->data[$form['field']] = $query;
            }
        }
        $this->init();
        return view('admincrud.add', ['data' => $this->data]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['form'] = $this->form;
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed
     */
    public function detail($id): mixed
    {
        $query = $this->findMix($this->model, $this->head, $id);
        $this->find = $query[0];
        $this->title = 'Detail of ' . $this->model->moduleName;
        $this->data['detail'] = $this->model->detail;
        $this->init();
        return view('admincrud.detail', ['data' => $this->data]);


    }
}
