<?php

namespace App\Http\Controllers\admin;

use App\Models\Setting;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class SettingController extends LaraCRUDController
{
    /**
     * @param Setting $setting
     */
    public function __construct(Setting $setting)
    {
        parent::__construct();

        $this->model = $setting;
        $this->add = false;
        $this->title = "Setting";
        $this->delete = false;

        $this->head = [
            array('field' => 'name', 'title' => 'Name'),
            array('field' => 'logo', 'title' => 'Logo', 'type' => 'image'),
            array('field' => 'email', 'title' => 'Email'),
            array('field' => 'phone', 'title' => 'Phone'),
            array('field' => 'address', 'title' => 'Address'),
            array('field' => 'about', 'title' => 'About'),
            array('field' => 'facebook', 'title' => 'Facebook', 'view' => false),
            array('field' => 'tiktok', 'title' => 'Tiktok', 'view' => false),
            array('field' => 'instagram', 'title' => 'Instagram', 'view' => false),
            array('field' => 'youtube', 'title' => 'Youtube', 'view' => false),
        ];

        $this->form = [
            array('field' => 'name', 'title' => 'Name', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'logo', 'title' => 'Logo', 'type' => 'file', 'accept' => 'image/*'),
            array('field' => 'email', 'title' => 'Email', 'type' => 'email'),
            array('field' => 'phone', 'title' => 'Phone', 'type' => 'number'),
            array('field' => 'address', 'title' => 'Address', 'type' => 'text'),
            array('field' => 'about', 'title' => 'About', 'type' => 'text'),
            array('field' => 'facebook', 'title' => 'Facebook', 'type' => 'text'),
            array('field' => 'tiktok', 'title' => 'Tiktok', 'type' => 'text'),
            array('field' => 'instagram', 'title' => 'Instagram', 'type' => 'text'),
            array('field' => 'youtube', 'title' => 'Youtube', 'type' => 'text'),
        ];
    }

    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->result = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['back'] = $this->model->moduleName;
        $this->data['form'] = $this->form;
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }
}
