<?php

namespace App\Http\Controllers\admin;

use App\Models\Setting;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Artisan;

class SettingController extends LaraCRUDController
{
    /**
     * @param Setting $setting
     */
    public function __construct(Setting $setting)
    {
        parent::__construct();

        $this->model = $setting;
        $this->add = true;
        $this->delete = false;


        $this->head = [
            array('field' => 'default_font', 'title' => 'Default Font'),
            array('field' => 'navbar_font', 'title' => 'Navbar Font'),
            array('field' => 'title_font', 'title' => 'Title Font'),
            array('field' => 'paragraph_font', 'title' => 'Paragraph Font'),
            array('field' => 'paragraph_line_height', 'title' => 'Paragraph Line Height'),
            array('field' => 'logo', 'title' => 'Logo', 'type' => 'image'),
           
        ];

        $this->form = [
            array('field' => 'default_font', 'title' => 'Default Font', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'navbar_font', 'title' => 'Navbar Font', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'title_font', 'title' => 'Title Font', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'paragraph_font', 'title' => 'Paragraph Font', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'paragraph_line_height', 'title' => 'Paragraph Line Height', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'logo', 'title' => 'Logo', 'type' => 'file', 'accept' => 'image/*'),
           
        ];
    }

    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->data['result'] = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['form'] = $this->form;
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }

    public function clearCache()
    {
        // Clear application cache
        Artisan::call('cache:clear');

        // Optionally, you can also clear configuration cache
        Artisan::call('config:clear');

        // Optionally, you can clear route cache
        Artisan::call('route:clear');

        // Optionally, you can clear view cache
        Artisan::call('view:clear');

       return redirect()->back();
    }
}
