<?php

namespace App\Http\Controllers\admin;

use App\Models\Social;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class SocialController extends LaraCRUDController
{
    public function __construct(Social $social)
    {
        $this->model = $social;

        $this->head = [
            array('field' => 'name', 'title' => 'Name'),
            array('field' => 'link', 'title' => 'Link'),
            array('field' => 'icon', 'title' => 'Icon', 'type' => 'image'),
        ];

        $this->form = [
            array('field' => 'name', 'title' => 'Name', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'link', 'title' => 'Link', 'type' => 'text', 'required' => true, 'validated' => 'required'),
            array('field' => 'icon', 'title' => 'Icon', 'type' => 'file', 'required' => true, 'validated' => 'required', 'accept' => 'image/*'),
        ];
    }

    /**
     * @return Application|Factory|View
     */
    public function getIndex(): View|Factory|Application
    {
        $this->data['result'] = $this->paginate();
        $this->init();
        return view('admin.index', ['data' => $this->data]);
    }

    /**
     * @return Factory|View|Application
     */
    public function getAdd(): Factory|View|Application
    {
        $this->data['form'] = $this->form;
        $this->init();
        return view('admin.add', ['data' => $this->data]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function detail($id): mixed
    {
        $this->data['find'] = $this->model->findOrFail($id);
        $this->init();
        return view('admin.detail', ['data' => $this->data]);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function getEdit($id): mixed
    {
        $this->data['back'] = $this->model->moduleName;
        $this->data['form'] = $this->form;
        $this->form[2] = array('field' => 'icon', 'title' => 'Icon', 'type' => 'file', 'accept' => 'image/*');
        $this->init();
        return parent::getEdit($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function update(Request $request): mixed
    {
        $this->form[2] = array('field' => 'icon', 'title' => 'Icon', 'type' => 'file', 'accept' => 'image/*');
        return parent::update($request);
    }
}
